sudo: false
language: node_js
node_js:
  - "4.0"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - ./node_modules/.bin/bower install;
  - npm install;
script:
  - npm run test;
after_success:
  - npm install coveralls@2.10.0 && cat ./coverage/lcov/lcov.info | coveralls